
const main = async (req, res, next) => {
    try {
        // Validar esquema

        // Enviar al servicio los datos

        // Devolver respuesta

        
    } catch (error) {
        next(error)
    }
}